USE [JTBD]
GO

/****** Object:  Table [dbo].[Groups]    Script Date: 18/9/2025 15:57:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Groups](
	[IdGroup] [int] IDENTITY(1,1) NOT NULL,
	[ProjectIdProject] [int] NOT NULL,
	[GroupName] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Grupos] PRIMARY KEY CLUSTERED 
(
	[IdGroup] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Groups]  WITH CHECK ADD  CONSTRAINT [FK_Groups_Projects] FOREIGN KEY([ProjectIdProject])
REFERENCES [dbo].[Projects] ([IdProject])
GO

ALTER TABLE [dbo].[Groups] CHECK CONSTRAINT [FK_Groups_Projects]
GO


